### ISSUE TITLE
Not finding images inside html files

### ISSUE THREAD

**Issue by Maqerfoo** [nuthrash/obsidian-html-plugin#11]
Images inside the html files does not render when I open them in Obsidian
![image](https://user-images.githubusercontent.com/63002176/232767293-1ec20400-1f89-4de8-bbfa-d991a5a817b7.png)

If I open the same file in firefox I see the images just fine

Here is an example of the html code for the image

`body data-absolute-enabled="true" style="font-family:Calibri;font-size:11pt">
		<div style="position:absolute;left:48px;top:115px;width:720px">
			<img width="857" height="624" src="tkcyvllwly.png" data-src-type="image/png" />
			<br />`

I have the operating mode for your plugin set to "low restricted mode"

**Comment by nuthrash** [comment]
The HTML code example `src="tkcyvllwly.png"`  means the image source is local image file `tkcyvllwly.png`, and the Obsidian app would block this image loading method. You could refer to [Known issues](https://github.com/nuthrash/obsidian-html-plugin#known-issues) "Cannot see local image files like `<img src="./image1.jpg" />` or `<img src="file:///C:/image1.jpg" />`" for detail explanation and try to modify original HTML files.

**Comment by Maqerfoo** [comment]
Derp. Well that figures.

To those who might find some utility from it, I wrote a Python script that converts a folder and subfolders of html files with pointers to images in the same folder, into self-contained html

https://gist.github.com/Maqerfoo/156a5887ea5d92be900f788c9451c001
