### ISSUE TITLE
Feature request: run a command or script after generating HTML

### ISSUE THREAD

**Issue by kintarowonders** [nuthrash/obsidian-html-plugin#15]
I like your plugin, and I think you should be able to optionally specify a command or script that it runs after generating the HTML. This could then mean a user can use scripts to automatically upload files by a number of means to their server or hosting.

**Comment by nuthrash** [comment]
Sorry, I think your feature request is out of the specification of this plugin. This plugin is just a HTML "reader", not a HTML "executor" nor a HTML "editor/modifier". And your feature request seems violate the official  Obsidian's [developer policies](https://docs.obsidian.md/Developer+policies) or [plugin security guideline](https://docs.obsidian.md/Plugins/Releasing/Plugin+guidelines#Security). Therefore, I cannot accept your feature request.
