### ISSUE TITLE
Feature Request: Obsidian shortcuts are invalid

### ISSUE THREAD

**Issue by jerviscui** [nuthrash/obsidian-html-plugin#16]
Obsidian shortcuts are invalid.

How to implement sending shortcuts back to Obsidian, like in the document editor.

**Comment by nuthrash** [comment]
Could you describe more detail about "sending shortcuts back to Obsidian"? 
Press keyboard shortcut, then go back to editing mode? (HTML reader plugin does not have editing mode)

**Comment by jerviscui** [comment]
Sorry.
I'll elaborate.

Obsidian keyboard shortcuts would not work if the focus is on the HTML Reader, you have to click on the title bar to get the focus on Obsidian to use the shortcuts.

Click on the red box,
![image](https://github.com/nuthrash/obsidian-html-plugin/assets/6396748/89ecc3ab-ad66-4233-b106-dda273c2b330)

Then shift + ctrl + f to work.

**Comment by nuthrash** [comment]
OK, I understand what you want. I think your feature request can be accomplished. 
And I will implement it for next version in this month or next month(maybe after merged with other features).
