### ISSUE TITLE
FR: Custom extensions

### ISSUE THREAD

**Issue by gerroon** [nuthrash/obsidian-html-plugin#18]
Hi

It would be nice if one could let the extension to read certain files as html files too. I have some files that are basically htmls but they do not have .html or .htm extensions coming from other apps so I ant rename them.

thanks

**Comment by nuthrash** [comment]
Sorry, this plugin is registered with file extensions .html and .html, and the Obsidian app would invoke this plugin according these file extensions. Therefore, your FR might not be accomplished with official Obsidian plugin calling mechanism.

I am sorry late to reply you, there is something wrong with GitHub's notification flow, I did not receive any notification about your issue.

**Comment by nuthrash** [comment]
I found a way to accomplished your RP, but it need restart the Obsidian app itself to bypass official plugin invoking mechanism. I am not sure this approach would violate any rule or not, so I would take some time to check related documents. If everything fine, I will add the new feature in next version.
