### ISSUE TITLE
How to build it?

### ISSUE THREAD

**Issue by nsuvorov83** [nuthrash/obsidian-html-plugin#2]
Instructions how to build were not found in README.MD. Please clarify this.

**Comment by nuthrash** [comment]
No need to build obsidian-html-plugin from source code. You can get the compiled plugin files `main.js` and `manifest.json` from Releases panel(https://github.com/nuthrash/obsidian-html-plugin/releases). Then follow the instructions of "[Manually installing the plugin](https://github.com/nuthrash/obsidian-html-plugin#manually-installing-the-plugin)" to put these two files to your vault's plugins folder.

**Comment by nuthrash** [comment]
If you want to build this project from source code, please refer to updated README.md paragraph [How to build this plugin from source code](https://github.com/nuthrash/obsidian-html-plugin#how-to-build-this-plugin-from-source-code).
