### ISSUE TITLE
Why open html file shows a blank space

### ISSUE THREAD

**Issue by Tlijia** [nuthrash/obsidian-html-plugin#20]
I'm using SingleFile to archive website into a single html file. 

 and it shows a blank space ,like this
<img width="1564" alt="image" src="https://github.com/nuthrash/obsidian-html-plugin/assets/18083859/5b753f78-2b27-43b6-b121-9340b58dd7f7">

the website is https://time.geekbang.org/column/article/39922

**Comment by nuthrash** [comment]
Please attach your html file to let me see its content.

**Comment by Tlijia** [comment]
[开篇词 _ 从今天起，跨过“数据结构与算法”这道坎 (2023_11_22 23_52_54).html.zip](https://github.com/nuthrash/obsidian-html-plugin/files/13461070/_.2023_11_22.23_52_54.html.zip)

here is the file

**Comment by nuthrash** [comment]
> [開篇詞 _ 從今天起，跨過“資料結構與演算法”這道檻 (2023_11_22 23_52_54).html.zip](https://github.com/nuthrash/obsidian-html-plugin/files/13461070/_.2023_11_22.23_52_54.html.zip)
> 
> here is the file

Hmm, I think this HTML file has something conflict with this plugin's keyboard events, so its content soon flash out as a white page as you seen.
I will try to resolve this problem, and it may need a while.

**Comment by Tlijia** [comment]
thank you very much !!!
