### ISSUE TITLE
Display HTML in markdown files?

### ISSUE THREAD

**Issue by vinhquach** [nuthrash/obsidian-html-plugin#21]
Hi,

Thank you for a great plugin.
I'm wondering if you could also make it display HTML in markdown files. For instance, we put the html source into a code block starting with ```html.

Best!

**Comment by hruzgar** [comment]
I think it would be even better if we just could embed a html page in a markdown. 

For example 
```
![[test-page.html]]
```
Would be too good to be true

**Comment by nuthrash** [comment]
> Hi,
> 
> Thank you for a great plugin. I'm wondering if you could also make it display HTML in markdown files. For instance, we put the html source into a code block starting with ```html.
> 
> Best!

You can put HTML code directly in the Markdown files, for example:
```md
**Bold Word**

<b>Bold Word</b>
```
However, there are many restrictions of HTML code inside Markdown files, you could google and learn from many sites.

**Comment by vinhquach** [comment]
I know about HTML-supported Live Preview mode. What I'm wondering is if you could also allow embedding HTML with style and script in markdown files and then view them properly in Reading mode. Like features of this plugin: https://github.com/Darakah/obsidian-fountain
- Obsidian support for .fountain files (Edit and render .fountain files from inside obsidian)
- Obsidian Block to render fountain script inside md notes

**Comment by nuthrash** [comment]
> I know about HTML-supported Live Preview mode. What I'm wondering is if you could also allow embedding HTML with style and script in markdown files and then view them properly in Reading mode. Like features of this plugin: https://github.com/Darakah/obsidian-fountain
> 
>     * Obsidian support for .fountain files (Edit and render .fountain files from inside obsidian)
> 
>     * Obsidian Block to render fountain script inside md notes

Hmm, I think what you need is a whole new plugin.
Because this plugin is just a pure HTML file reader, it would not participate with any Markdown file.

**Comment by vinhquach** [comment]
Thank you for making that clear.
