### ISSUE TITLE
[Feature] Zoom support

### ISSUE THREAD

**Issue by scruel** [nuthrash/obsidian-html-plugin#8]

**Comment by nuthrash** [comment]
It seems that there is no easy way to implement this feature in few days, therefore I need some weeks to survey and try to implement it on Obsidian platform. Please be patience for waiting status update.

**Comment by nuthrash** [comment]
Hello @scruel,

I have implement the zoom feature on the version 1.0.8 of the this plugin.
You could update to latest version and try to use it to see if something wrong.
