### ISSUE TITLE
[Feature] Search support

### ISSUE THREAD

**Issue by scruel** [nuthrash/obsidian-html-plugin#9]

**Comment by nuthrash** [comment]
It seems that there is no easy way to implement this feature in few days, therefore I need some weeks to survey and try to implement it on Obsidian platform. Please be patience for waiting status update.

**Comment by nuthrash** [comment]
Status Report:
- [x] Main feature implementation
- [ ] HotKeys/Commands management and configuration interface
- [ ] Touch gestures management and configuration interface on mobile devices
- [ ] Test and fine tune

Screenshot:
![obsidian-html-plugin_search1](https://user-images.githubusercontent.com/43021861/227202481-804c7b6e-a119-48e1-8344-221904c546bc.gif)

**Comment by nuthrash** [comment]
Hello @scruel,

I have implement the search feature on the version 1.0.8 of the this plugin.
You could update to latest version and try to use it to see if something wrong.
